language: go
go:
  - 1.10
  - 1.11
  - 1.12.13
  - 1.13

script:
  - go test -v ./...

before_install:
  - pip install --user codecov
after_success:
  - codecov --file coverage/lcov.info --disable search